#! /bin/sh
#
# T S T
#
# tst last edited on Fri Jun 21 23:26:28 2024 
#
# To redirect both stdout and stderr to a file, use ampersand redirect operation, for example; -
#  ./tst &> outputFile
#
EXE=csvstats
TEN_PLUSS=++++++++++
#
# Test if no options mode has any sensitivity to file length or number of columns
echo ""
echo "${TEN_PLUSS} $EXE small.csv  +++Small valid 2 column file, no options check${TEN_PLUSS}"
../$EXE small.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small valid file small.csv, no options check${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -H small.csv  +++Small valid 2 column file, with header option check${TEN_PLUSS}"
../$EXE -H small.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small valid file small.csv, with header option check${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -H -n small.csv  +++Small valid 2 column file, with header and extra line options check${TEN_PLUSS}"
../$EXE -H -n small.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small valid file small.csv, with header and extra line options check${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE cols7rows4.csv +++Small valid 7 column file and no options check${TEN_PLUSS}"
../$EXE cols7rows4.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small valid file tmp.csv, no options check${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE heights.csv +++Somewhat longer file with 2 columns, 1 column the reverse of the other${TEN_PLUSS}"
../$EXE heights.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small file with lengthier lines${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_PiDigits.dat +++Long file of 1 column of single digits, no options check${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_PiDigits.dat
echo "${TEN_PLUSS} Shell got Return code number $? for long file with single column (4.5348, 2.86733906028871)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_Lew.dat +++Long file of 1 column of single digits, no options check${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_Lew.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 200 long file with single column (-177.435, 277.332168044316)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_Lottery.dat +++Long file of 1 column of single digits, no options check${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_Lottery.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 218 long file with single column (518.958715596330, 291.699727470969)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_Mavro.dat +++Long file of 1 column of single digits, no options check${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_Mavro.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 50 long file with single column (2.001856, 0.000429123454003053)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_Michelso.dat +++Long file of 1 column of single digits, no options check${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_Michelso.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 100 long file with single column (299.8524, 0.0790105478190518)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_NumAcc1.dat  +++NIST numerical accuracy file of 3 large close numbers${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_NumAcc1.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 1st NIST numerical accuracy file ( 10000002, 1)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_NumAcc2.dat  +++NIST numerical accuracy file of close numbers${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_NumAcc2.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 2nd NIST numerical accuracy file ( 1.2, 0.1)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_NumAcc3.dat  +++NIST numerical accuracy file of close numbers${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_NumAcc3.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 3rd NIST numerical accuracy file (1000000.2, 0.1)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_NumAcc4.dat  +++NIST numerical accuracy file of large close numbers${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_NumAcc4.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 4th NIST numerical accuracy file (10000000.2, 0.1)${TEN_PLUSS}"
#
echo ""
echo ${TEN_PLUSS} '$EXE -H -c "!" -d ";" data.txt  +++ file with semi colon as the separator between colummns'${TEN_PLUSS}
../$EXE -H -c "!" -d ";" data.txt
echo "${TEN_PLUSS} Shell got Return code number $? for semi colon column separator file${TEN_PLUSS}"
#
echo ""
echo ${TEN_PLUSS} '$EXE -H -d "\\t" data.tab  +++ file with ASCII horizontal tab as the separator between colummns'${TEN_PLUSS}
../$EXE -H -d "\t" data.tab
echo "${TEN_PLUSS} Shell got Return code number $? for tab column separator file${TEN_PLUSS}"
#
echo ""
echo ${TEN_PLUSS} '$EXE -H -d "\\x9" data.tab  +++ file with ASCII horizontal tab (Hex value 0x09) as the column separator'${TEN_PLUSS}
../$EXE -H -d "\x9" data.tab
echo "${TEN_PLUSS} Shell got Return code number $? for tab column separator file${TEN_PLUSS}"
#
echo ""
echo ${TEN_PLUSS} '$EXE -H -d " " data.dat  +++ file with just ASCII space as the separator between colummns'${TEN_PLUSS}
../$EXE -H -d " " data.dat
echo "${TEN_PLUSS} Shell got Return code number $? for space column separator file${TEN_PLUSS}"
#
echo ""
echo ${TEN_PLUSS} 'cat data.csv | $EXE -v -o stdinTest.tst  +++stdin input with file output check'${TEN_PLUSS}
cat data.csv | ../$EXE -v -o stdinTest.tst
echo "${TEN_PLUSS} Shell got Return code number $? for input through stdin and output to a File${TEN_PLUSS}"
echo "${TEN_PLUSS} cat stdinTest.tst  +++show output file check${TEN_PLUSS}"
cat stdinTest.tst
echo "${TEN_PLUSS} Shell got Return code number $? for File output${TEN_PLUSS}"
#
#echo ""
#echo "${TEN_PLUSS} $EXE -vVh  +++Usage/help verbose and version information check${TEN_PLUSS}"
#../$EXE -vVh
#echo "${TEN_PLUSS} Shell got Return code number $? for usage/help, version and verbose options${TEN_PLUSS}"
#
#echo ""
#echo "${TEN_PLUSS} $EXE -v john3_16.txt gen1_1.txt test.txt +++check multilpe file input${TEN_PLUSS}"
#../$EXE -v john3_16.txt gen1_1.txt test.txt
#echo "${TEN_PLUSS} Shell got Return code number $? for multiple file input check${TEN_PLUSS}"
#
#echo ""
#echo "${TEN_PLUSS} $EXE wikipedia.hex checkSumErr.hex  +++2 Files one of which has checksum Error check${TEN_PLUSS}"
#../$EXE wikipedia.hex checkSumErr.hex
#echo "${TEN_PLUSS} Shell got Return code number $? for 2 Files one of which has checksum Error File check${TEN_PLUSS}"
#
#echo ""
#echo "${TEN_PLUSS} cat wikipedia.hex | $EXE  +++Test pipe into stdin${TEN_PLUSS}"
#cat wikipedia.hex | ../$EXE
#echo "${TEN_PLUSS} Shell got Return code number $? for Test pipe into stdin${TEN_PLUSS}"
