#! /bin/sh
#
# T S T
#
# tst last edited on Fri Jun 21 23:26:28 2024 
#
# To redirect both stdout and stderr to a file, use ampersand redirect operation, for example; -
#  ./tst &> outputFile
#
EXE=csvstats
TEN_PLUSS=++++++++++
#
# Test if no options mode has any sensitivity to file length or number of columns
echo ""
echo "${TEN_PLUSS} $EXE small.csv  +++Small valid 2 column file, no options check${TEN_PLUSS}"
../$EXE small.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small valid file small.csv, no options check${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -H small.csv  +++Small valid 2 column file, with header option check${TEN_PLUSS}"
../$EXE -H small.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small valid file small.csv, with header option check${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -H -n small.csv  +++Small valid 2 column file, with header and extra line options check${TEN_PLUSS}"
../$EXE -H -n small.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small valid file small.csv, with header and extra line options check${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE cols7rows4.csv +++Small valid 7 column file and no options check${TEN_PLUSS}"
../$EXE cols7rows4.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small valid file tmp.csv, no options check${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE heights.csv +++Somewhat longer file with 2 columns, 1 column the reverse of the other${TEN_PLUSS}"
../$EXE heights.csv
echo "${TEN_PLUSS} Shell got Return code number $? for small file with lengthier lines${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_PiDigits.dat +++Long file of 1 column of single digits, no options check${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_PiDigits.dat
echo "${TEN_PLUSS} Shell got Return code number $? for long file with single column (4.5348, 2.86733906028871)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_NumAcc1.dat  +++NIST numerical accurracy file of 3 large close numbers${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_NumAcc1.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 1st NIST numerical accuracy file ( 10000002, 1)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_NumAcc2.dat  +++NIST numerical accurracy file of close numbers${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_NumAcc2.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 2nd NIST numerical accuracy file ( 1.2, 0.1)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_NumAcc3.dat  +++NIST numerical accurracy file of close numbers${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_NumAcc3.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 3rd NIST numerical accuracy file (1000000.2, 0.1)${TEN_PLUSS}"
#
echo ""
echo "${TEN_PLUSS} $EXE -HMNnPRp NIST_StRD_NumAcc4.dat  +++NIST numerical accurracy file of large close numbers${TEN_PLUSS}"
../$EXE -HMNnPRp NIST_StRD_NumAcc4.dat
echo "${TEN_PLUSS} Shell got Return code number $? for 4th NIST numerical accuracy file (10000000.2, 0.1)${TEN_PLUSS}"
#
#echo ""
#echo '${TEN_PLUSS} cat gen1_1.txt | $EXE -v -o stdinTest.tst  +++stdin input with file output check${TEN_PLUSS}'
#cat gen1_1.txt | ../$EXE -v -o stdinTest.tst
#echo "${TEN_PLUSS} Shell got Return code number $? for input through stdin and output to a File${TEN_PLUSS}"
#echo '${TEN_PLUSS} cat stdinTest.tst  +++show output file check${TEN_PLUSS}'
#cat stdinTest.tst
#echo "${TEN_PLUSS} Shell got Return code number $? for File output${TEN_PLUSS}"
#
#echo ""
#echo "${TEN_PLUSS} $EXE -vVh  +++Usage/help verbose and version information check${TEN_PLUSS}"
#../$EXE -vVh
#echo "${TEN_PLUSS} Shell got Return code number $? for usage/help, version and verbose options${TEN_PLUSS}"
#
#echo ""
#echo "${TEN_PLUSS} $EXE -v john3_16.txt gen1_1.txt test.txt +++check multilpe file input${TEN_PLUSS}"
#../$EXE -v john3_16.txt gen1_1.txt test.txt
#echo "${TEN_PLUSS} Shell got Return code number $? for multiple file input check${TEN_PLUSS}"
#
#echo ""
#echo "${TEN_PLUSS} $EXE wikipedia.hex checkSumErr.hex  +++2 Files one of which has checksum Error check${TEN_PLUSS}"
#../$EXE wikipedia.hex checkSumErr.hex
#echo "${TEN_PLUSS} Shell got Return code number $? for 2 Files one of which has checksum Error File check${TEN_PLUSS}"
#
#echo ""
#echo "${TEN_PLUSS} cat wikipedia.hex | $EXE  +++Test pipe into stdin${TEN_PLUSS}"
#cat wikipedia.hex | ../$EXE
#echo "${TEN_PLUSS} Shell got Return code number $? for Test pipe into stdin${TEN_PLUSS}"
